### ISSUE TITLE
relase flexdecrypt.deb installed , but error 

### ISSUE THREAD

**Issue by SecurityLife** [JohnCoates/flexdecrypt#1]
The first error is :
iPhone:~/flex_decrypt root# ./flexdecrypt 
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/root/flex_decrypt/./flexdecrypt
  Reason: image not found
Abort trap: 6

That I cp flex.app/Framework/* to /usr/lib the other error appear : 

dyld: Symbol not found: _$s17StringLiteralTypes013ExpressibleByaB0PTl
  Referenced from: /usr/bin/flexdecrypt
  Expected in: /usr/lib/libswiftCore.dylib
 in /usr/bin/flexdecrypt
Abort trap: 6

**Comment by JohnCoates** [comment]
Try the latest release: https://github.com/JohnCoates/flexdecrypt/releases/latest

**Comment by JohnCoates** [comment]
Just tested on iOS 9 and the update fixes this issue.
