### ISSUE TITLE
Flexdecrypt binary uses

### ISSUE THREAD

**Issue by Dershowitz011** [JohnCoates/flexdecrypt#2]
What exactly can OR should be done with the `Flexdecrypt` binary in releases? Do help. Thanks.

**Comment by JohnCoates** [comment]
Transfer it to your device and run it. A location that is on `$PATH` is ideal, such as /usr/bin. Otherwise just install the .deb with Filza or `dpkg -i flexdecrypt.deb`

**Comment by Dershowitz011** [comment]
Okay. I'll try it out once I'm jailbroken. Thanks!

**Comment by JohnCoates** [comment]
You're welcome. I've added a note about it in the readme.
