### ISSUE TITLE
Release 1.1 deb package doesn't work on iOS 10.3.3 Jalibreak device.

### ISSUE THREAD

**Issue by SecurityLife** [JohnCoates/flexdecrypt#3]
I try to reinstall the deb package , but still un work . 

iPhone:/usr/lib root# flexdecrypt 

dyld: Library not loaded: @rpath/libswiftCore.dylib

  Referenced from: /usr/bin/flexdecrypt

  Reason: no suitable image found.  Did find:

	/usr/lib/libswift/stable/libswiftCore.dylib: file system sandbox blocked mmap() of '/usr/lib/libswift/stable/libswiftCore.dylib'

Abort trap: 6

I think if can include depend dylib to the deb , can fix the problem ?

That I download source code wana to compile it , but meet another problem .

Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the com.apple.diagnosticd.diagnostic,

com.apple.frontboard.debugapplications,

com.apple.multitasking.termination,

com.apple.private.cs.debugger,

com.apple.private.security.no-sandbox,

com.apple.private.skip-library-validation,

com.apple.springboard.launchapplications,

dynamic-codesigning,

platform-application,

and task_for_pid-allow entitlements and doesn't match the entitlements file's values for the application-identifier and com.apple.developer.team-identifier entitlements.

When I click the automatically manager signing , will appear this problem in MacOs 11 && XCode 12 .

**Comment by JohnCoates** [comment]
I believe this is an issue only present with your jailbreak. Are you using H3lix? Have you asked the developers of that jailbreak about it?

**Comment by SecurityLife** [comment]
I fix in yesterday, Let flexdecrypted worked when I change Xcode 11 to compile .

**Comment by JohnCoates** [comment]
Okay great! So the solution is using Xcode 11+. Thanks for the heads up.
