### ISSUE TITLE
Invalid Mach-O magic

### ISSUE THREAD

**Issue by haniag** [JohnCoates/flexdecrypt#4]
Running iPhone 6S 13.5 on latest Checkra1n. I installed in device through packaged deb file.

I have the ipa file on device that I downloaded from App Store. When I run comment "flexdecrypt file.ipa" I get:

Fatal error: Invalid Mach-O magic: 67324752: file /Users/macbook/Dev/Projects/flexdecrypt/Source/Mach-O/MachoBinary.swift, line 45
Trace/BPT trap: 5

**Comment by JohnCoates** [comment]
You need to extract the ipa and pass the path to the app executable or a framework Mach-o file

**Comment by haniag** [comment]
I extracted the ipa and when I ran

    flexdecrypt 2/Payload/myApp.app/Frameworks/myApp.framework/myAppCore
I get

    Error: mremap_encryptedFailed(segment: "__TEXT", error: "#1: Operation not permitted")

However, the operation is successful when doing it on an installed application. I thought I can do this on whether an app is installed or not, so maybe I misunderstood.

**Comment by JohnCoates** [comment]
It doesn't have to be installed, but you need to be licensed to decrypt it. FairPlay encryption is cryptographically secure, so if you don't have the keys on-device to decrypt the app then it's impossible to.
