### ISSUE TITLE
Sometimes stuck at Data.append

### ISSUE THREAD

**Issue by DarcyIW** [JohnCoates/flexdecrypt#6]
Hi，I have tried several Apps(>10)，and found about half of them succeeded and half of them stuck at 
`decryptedData.append(pointer, count: fileSize)`.

Terminal output is 
```
Mapped __TEXT to 13b26c000 - bytes: 6704000
Mapped __DATA to 141970000 - bytes: 1840000
Mapped __RODATA to 14326c000 - bytes: fd0000
Mapped __LINKEDIT to 14423c000 - bytes: b98f10
Allowing invalid codesigned memory
Remapping __TEXT to encrypted backing
Reading decrypted file
Bytes: 9aacf10
Reading 6704000 bytes at 13b26c000
```
And stuck at this.

**Comment by Halo-Michael** [comment]
Same, iOS13.4.1 iPhone7, wanna decrypt Skyhill.

**Comment by JohnCoates** [comment]
Do you have any examples of free apps this occurs with? I haven't been able to reproduce this issue.

**Comment by Halo-Michael** [comment]
To reproduce this problem, it seems that two conditions need to be met: the app needs pay; the account to which the app belongs has never been logged in on the device.
3utool used to have a function to download pirated paid programs, but it has already canceled this function. Unfortunately, I have not downloaded much apps that meet these two conditions, so it is difficult to be 100% sure.

**Comment by Halo-Michael** [comment]
Correction: Just need the apple id to which the app belongs has never been logged in on your device. I tried to download a free application using 3utools, and it also could not be decrypted.

**Comment by JohnCoates** [comment]
This is not a tool for piracy. It's for research.

You need to be licensed to decrypt the app, that means having signed into the account that the app was originally downloaded with. FairPlay encryption is cryptographically secure, so if you don't have the keys on-device to decrypt the app then it's impossible to do that.
