### ISSUE TITLE
这是咋回事

### ISSUE THREAD

**Issue by mrfuturman** [JohnCoates/flexdecrypt#7]
Provisioning profile "123" doesn't include the com.apple.diagnosticd.diagnostic,
com.apple.frontboard.debugapplications,
com.apple.multitasking.termination,
com.apple.private.cs.debugger,
com.apple.private.security.no-sandbox,
com.apple.private.skip-library-validation,
com.apple.springboard.launchapplications,
dynamic-codesigning,
platform-application,
and task_for_pid-allow entitlements and doesn't match the entitlements file's values for the com.apple.developer.team-identifier and application-identifier entitlements.

**Comment by JohnCoates** [comment]
Don't set codesigning to be configured automatically. Check the Codesigning build script to see how it works. It signs with the `codesign` utility after automatically choosing your Xcode wildcard provisoning profile.
